from opentrons import protocol_api
import json
import re

# Double braces { } escape dictionaries so Python generation doesn't break
metadata = {
    "description": "Dynamic Protocol - Iteration 3",
    "author": "Auto-Generated by BO Script"
}

requirements = {"robotType": "Flex", "apiLevel": "2.23"}


def run(protocol: protocol_api.ProtocolContext):

    # --- INJECTED DATA ---
    data = [
    {
        "s1": 4.0,
        "s2": 0.0,
        "s3": 0.0,
        "s4": 4.0,
        "s5": 0.0,
        "s6": 0.0,
        "s7": 0.0,
        "s8": 0.0,
        "IBP": 180.0,
        "LOV": 0.0,
        "DCF": 0.0,
        "GLV": 0.0,
        "dmso": 0.0,
        "water": 1192.0,
        "next_plate_well": "C11",
        "next_deepplate_well": "C11",
        "replicates": 2
    },
    {
        "s1": 0.0,
        "s2": 0.0,
        "s3": 0.0,
        "s4": 0.0,
        "s5": 0.0,
        "s6": 4.0,
        "s7": 0.0,
        "s8": 4.0,
        "IBP": 180.0,
        "LOV": 0.0,
        "DCF": 0.0,
        "GLV": 0.0,
        "dmso": 0.0,
        "water": 1192.0,
        "next_plate_well": "D1",
        "next_deepplate_well": "D1",
        "replicates": 2
    },
    {
        "s1": 0.0,
        "s2": 0.0,
        "s3": 4.0,
        "s4": 0.0,
        "s5": 4.0,
        "s6": 0.0,
        "s7": 0.0,
        "s8": 0.0,
        "IBP": 180.0,
        "LOV": 0.0,
        "DCF": 0.0,
        "GLV": 0.0,
        "dmso": 0.0,
        "water": 1192.0,
        "next_plate_well": "D3",
        "next_deepplate_well": "D3",
        "replicates": 2
    },
    {
        "s1": 0.0,
        "s2": 4.0,
        "s3": 0.0,
        "s4": 0.0,
        "s5": 0.0,
        "s6": 0.0,
        "s7": 4.0,
        "s8": 0.0,
        "IBP": 180.0,
        "LOV": 0.0,
        "DCF": 0.0,
        "GLV": 0.0,
        "dmso": 0.0,
        "water": 1192.0,
        "next_plate_well": "D5",
        "next_deepplate_well": "D5",
        "replicates": 2
    }
]

    protocol.comment(f"Starting Batch Run with {len(data)} samples.")

    # --- ROBOT SETUP ---
    # Rack 0 (Default)
    tip1000_1 = protocol.load_labware(load_name="opentrons_flex_96_filtertiprack_1000ul", location="B1")
    # Rack 1 (Overflow)
    tip1000_2 = protocol.load_labware(load_name="opentrons_flex_96_filtertiprack_1000ul", location="A1")
    
    tip50 = protocol.load_labware(load_name="opentrons_flex_96_filtertiprack_50ul", location="B2")

    hs_mod = protocol.load_module(module_name="heaterShakerModuleV1", location="D1")
    hs_adapter = hs_mod.load_adapter("opentrons_universal_flat_adapter")
    pr_mod = protocol.load_module(module_name="absorbanceReaderV1", location="C3")

    pipette_low = protocol.load_instrument(instrument_name="flex_1channel_50", mount="right", tip_racks=[tip50])
    pipette_high = protocol.load_instrument(instrument_name="flex_1channel_1000", mount="left", tip_racks=[tip1000_1, tip1000_2])

    # --- TIP TRACKING INJECTION ---
    # This sets the STARTING point for the entire batch.
    # The robot automatically increments to the next tip after every usage.
    rack_id_1000 = "0" 
    start_well_1000 = "A10"
    
    tipracks_1000 = {"0": tip1000_1, "1": tip1000_2}
    
    pipette_high.starting_tip = tipracks_1000[rack_id_1000].wells_by_name()[start_well_1000]
    
    start_well_50 = "G4"
    pipette_low.starting_tip = tip50.wells_by_name()[start_well_50]


    # --- LABWARE SETUP ---
    surfactant_stock_1 = protocol.load_labware(load_name="allenlab_8_wellplate_20000ul", location="C1")
    s1 = surfactant_stock_1['A1']
    s2 = surfactant_stock_1['A2']
    s3 = surfactant_stock_1['A3']
    s4 = surfactant_stock_1['A4']
    s5 = surfactant_stock_1['B1']
    s6 = surfactant_stock_1['B2']
    s7 = surfactant_stock_1['B3']
    s8 = surfactant_stock_1['B4']

    surfactant_drug_dmso_stock_2 = protocol.load_labware(load_name="allenlab_8_wellplate_20000ul", location="C2")
    ibp = surfactant_drug_dmso_stock_2['B1']
    lov = surfactant_drug_dmso_stock_2['B2']
    dcf = surfactant_drug_dmso_stock_2['B3']
    glv = surfactant_drug_dmso_stock_2['B4']
    water = surfactant_drug_dmso_stock_2['A1']
    
    plate = protocol.load_labware(load_name="corning_96_wellplate_360ul_flat_new", location='D2')
    next_plate_well = 'C11'

    deepplate = hs_adapter.load_labware("corning_96_wellplate_360ul_flat_new")
    next_deepplate_well = 'C11'

    trash = protocol.load_trash_bin(location="A3")

    sources = {
        's1': s1, 's2': s2, 's3': s3, 's4': s4, 's5': s5, 's6': s6, 's7': s7, 's8': s8,
        'water': water,
        'IBP': ibp, 'LOV': lov, 'DCF': dcf, 'GLV': glv,
    }
    
    protocol.comment("Labware loaded. Starting experiment preparation.")

    # --- HELPER FUNCTIONS ---

    def next_well(well):
        match = re.match(r"([A-H])(\d+)", well)
        if not match:
            raise ValueError(f"Invalid well format: {well}")
        row, col = match.groups()
        col = int(col)
        if col < 12:
            col += 1
        else:
            col = 1
            row = chr(ord(row) + 1)
        return f"{row}{col}"
        
    surfactant_list = ['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8','water']
    drug_list = ['IBP', 'LOV', 'DCF', 'GLV']

    def pipette_selection (vol):
        if vol <= 40:
            return pipette_low
        else:
            return pipette_high
    
    def plate_on_hs(labware_to_shake, new_location, speed, time):
        hs_mod.close_labware_latch()
        hs_mod.set_and_wait_for_shake_speed(speed)
        protocol.delay(minutes=time)
        hs_mod.deactivate_shaker()
        hs_mod.open_labware_latch()
        protocol.move_labware(labware=labware_to_shake, new_location= new_location, pick_up_offset={'x': 0, 'y': 0, 'z':-2}, use_gripper=True)

    def plate_on_hs_to_reader(labware_to_shake, speed, time):
        hs_mod.close_labware_latch()
        hs_mod.set_and_wait_for_shake_speed(speed)
        protocol.delay(minutes=time)
        hs_mod.deactivate_shaker()
        hs_mod.open_labware_latch()

    def plate_on_pr(labware_to_read, new_location):
        pr_mod.close_lid()
        pr_mod.initialize(mode="single", wavelengths=[600])
        pr_mod.open_lid()
        protocol.move_labware(labware=labware_to_read, new_location=pr_mod, use_gripper=True)
        pr_mod.close_lid()
        
        pr_mod.read()
        pr_mod.read(export_filename=f"raw_absorbance_i3")
        
        pr_mod.open_lid()
        protocol.move_labware(labware=labware_to_read, new_location=new_location, use_gripper=True)
        pr_mod.close_lid()


    # --- CORE LOGIC ---
    
    def make_drug_or_surfactant(a_list, next_deepplate_well, row_of_data):
        for pipette in [pipette_low, pipette_high]:
            pipette.well_bottom_clearance.dispense = 25
            pipette.well_bottom_clearance.aspirate = 2      
       
        hs_mod.close_labware_latch()

        for n, item in enumerate(a_list):
            vol = float(row_of_data.get(item, 0))
            pipette = pipette_selection(vol)
            if vol > 0:
                pipette.pick_up_tip()
                pipette_high.flow_rate.dispense = 50
                air_gap_vol = 65 if pipette == pipette_high else 10
                
                pipette.transfer(vol, sources[item], deepplate[next_deepplate_well], new_tip='never', air_gap=air_gap_vol)
                pipette.blow_out(deepplate[next_deepplate_well].bottom(z=25))
                pipette.touch_tip(deepplate[next_deepplate_well], v_offset=15)
                pipette.drop_tip()  

        current_deepplate_well = next_deepplate_well
        next_deepplate_well = next_well(next_deepplate_well)
        return current_deepplate_well, next_deepplate_well

        
    def make_exp(current_drug_well, current_surfactant_well, next_plate_well):
        for pipette in [pipette_low, pipette_high]:
            pipette.well_bottom_clearance.dispense = 13
            pipette.well_bottom_clearance.aspirate = 2    
        
        replicate_wells = []
        for _ in range(2): 
            replicate_wells.append(next_plate_well)
            next_plate_well = next_well(next_plate_well)

        # Surfactant
        pipette_high.pick_up_tip()
        pipette_high.flow_rate.dispense = 50
        for well in replicate_wells:
            pipette_high.transfer(270, deepplate[current_surfactant_well], plate[well], new_tip='never', air_gap=60)
        pipette_high.drop_tip()

        # Drug
        pipette_low.pick_up_tip()
        for well in replicate_wells:
            pipette_low.transfer(30, deepplate[current_drug_well], plate[well], new_tip='never', air_gap=10) 
            pipette_low.flow_rate.dispense = 25
            pipette_low.blow_out(plate[well])
            pipette_low.touch_tip(plate[well], v_offset=-2)
        pipette_low.drop_tip()
        
        return next_plate_well
    

    # --- EXECUTION ROUTINE ---

    # PHASE 1: MAKE ALL DEEP WELL SOLUTIONS
    protocol.comment("Preparing drug and surfactant mixtures in deep well plate.")
    well_pairs = []
    
    for i in range(len(data)):
        row_of_data = data[i]
        
        current_surfactant_well, next_deepplate_well = make_drug_or_surfactant(surfactant_list, next_deepplate_well, row_of_data)
        current_drug_well, next_deepplate_well = make_drug_or_surfactant(drug_list, next_deepplate_well, row_of_data)
        well_pairs.append((current_drug_well, current_surfactant_well))  

    # PHASE 2: MIX (SHAKE)
    protocol.comment("Shaking deep well plate to mix components.")
    plate_on_hs(labware_to_shake=deepplate, new_location='A2', speed=1000, time=1)
    
    protocol.move_labware(
        labware=plate, 
        new_location=hs_adapter, 
        pick_up_offset={'x': 0, 'y': 0, 'z':-2}, 
        drop_offset={'x': 0, 'y': 0, 'z': -5}, 
        use_gripper=True
    )
    hs_mod.close_labware_latch()

    # PHASE 3: TRANSFER ALL TO EXPERIMENTAL PLATE
    protocol.comment("Pipetting mixtures to experimental plate.")
    for i in range(len(data)):
        row_of_data = data[i]
        current_drug_well, current_surfactant_well = well_pairs[i]
        next_plate_well = make_exp(current_drug_well, current_surfactant_well, next_plate_well)

    protocol.comment(f"Protocol delayed for 0 minutes")
    protocol.delay(minutes=float(0))
    
    protocol.comment("Shaking experimental plate before measurement.")
    plate_on_hs_to_reader(labware_to_shake=plate, time=1, speed=1000)
    
    protocol.comment("Measuring absorbance.")
    plate_on_pr(labware_to_read=plate, new_location="D2")
    
    protocol.move_labware(labware=deepplate, new_location=hs_adapter, use_gripper=True)
    pr_mod.close_lid()